apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: mydockerid/gateway-svc
        imagePullPolicy: Never
        env:
          - name: ClientApp
            value: https://app.carsties.store
          - name: IdentityServiceUrl
            value: http://identity-svc.carsties-domain.com
            # value: http://identity-clusterip
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 80